// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyEnglishServer.Data;

namespace StudyEnglishServer.Migrations
{
    [DbContext(typeof(StudyEnglishDBContext))]
    [Migration("20200607023357_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudyEnglishServer.Data.Models.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url");

                    b.Property<int?>("WordId");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("Audio");
                });

            modelBuilder.Entity("StudyEnglishServer.Data.Models.StudyHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Correct");

                    b.Property<DateTime>("Data");

                    b.Property<int?>("WordId");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("StudyHistory");
                });

            modelBuilder.Entity("StudyEnglishServer.Data.Models.Translate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPrimary");

                    b.Property<string>("Text");

                    b.Property<int?>("WordId");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("Translates");
                });

            modelBuilder.Entity("StudyEnglishServer.Data.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Association");

                    b.Property<string>("Text");

                    b.Property<string>("Transcription");

                    b.HasKey("Id");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("StudyEnglishServer.Data.Models.Audio", b =>
                {
                    b.HasOne("StudyEnglishServer.Data.Models.Word")
                        .WithMany("Audio")
                        .HasForeignKey("WordId");
                });

            modelBuilder.Entity("StudyEnglishServer.Data.Models.StudyHistory", b =>
                {
                    b.HasOne("StudyEnglishServer.Data.Models.Word")
                        .WithMany("StudyHistory")
                        .HasForeignKey("WordId");
                });

            modelBuilder.Entity("StudyEnglishServer.Data.Models.Translate", b =>
                {
                    b.HasOne("StudyEnglishServer.Data.Models.Word")
                        .WithMany("Translate")
                        .HasForeignKey("WordId");
                });
#pragma warning restore 612, 618
        }
    }
}
